main: eu.darkcube.system.skyland.Skyland
name: Skyland
author: BrickStacker_S
version: 1.0
api-version: 1.13
load: POSTWORLD
commands:
  gm:
  heal:
  day:
  night:
  fly:
  test:
  max:
  spawntrainingstand:
  god:
  trash:
  world:
  getitem:
  getgui:
