main: eu.darkcube.system.skyland.Skyland
name: Skyland
author: EliteDarkness
version: 1.0
api-version: 1.13
commands:
  gm:
  heal:
  day:
  night:
  fly:
  test:
  max:
  spawntrainingstand:
  god:
  trash:
  world:
  loadworld:
  unloadworld:
  createworld:
  getitem:
  getgui: