metadata.format.version = "1.1"

[versions]

cloudnet = "3.4.5-RELEASE"
bungee = "1.19-R0.1-SNAPSHOT"
luckperms = "5.4"
protocollib = "4.8.0"
viaversion = "4.7.0"

[libraries]

viaversion = { group = "com.viaversion", name = "viaversion-api", version.ref = "viaversion" }
viaversion-common = { group = "com.viaversion", name = "viaversion-common", version.ref = "viaversion" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocollib" }
bungee = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungee" }
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }

cloudnetDriver = { group = "de.dytanic.cloudnet", name = "cloudnet-driver", version.ref = "cloudnet" }
cloudnetBridge = { group = "de.dytanic.cloudnet", name = "cloudnet-bridge", version.ref = "cloudnet" }
cloudnet = { group = "de.dytanic.cloudnet", name = "cloudnet", version.ref = "cloudnet" }
cloudnetWrapper = { group = "de.dytanic.cloudnet", name = "cloudnet-wrapper-jvm", version.ref = "cloudnet" }

[bundles]

