metadata.format.version = "1.1"

[versions]

cloudnet = "4.0.0-RC10"
bungee = "1.19-R0.1-SNAPSHOT"
luckperms = "5.4"
protocollib = "4.8.0"
viaversion = "4.10.0-24w09a-darkcube-20240423.193857-1"
annotations = "24.1.0"
hologramlib = "2.6.0-SNAPSHOT"
velocity = "3.1.1"
jline = "3.25.0"
shadow = "8.1.2"
blossom = "1.3.1"
minestom = "7320437640"
minestom-extensions = "1.2.0"
paperweight-userdev = "1.5.12"
brigadier = "1.0.18"
gson = "2.10.1"
adventure = "4.16.0"
adventure-platform = "4.3.2"
jctools-core = "4.0.3"
fastutil = "8.5.13"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
adventure-text-serializer-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventure-text-serializer-gson-legacy-impl = { group = "net.kyori", name = "adventure-text-serializer-gson-legacy-impl", version.ref = "adventure" }
adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-platform-bukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventure-platform" }
brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
hologramlib = { group = "com.github.unldenis.hologram", name = "hologram-lib", version.ref = "hologramlib" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
viaversion = { group = "com.viaversion", name = "viaversion-api", version.ref = "viaversion" }
viaversion-common = { group = "com.viaversion", name = "viaversion-common", version.ref = "viaversion" }
viaversion-velocity = { group = "com.viaversion", name = "viaversion-velocity", version.ref = "viaversion" }
viaversion-bukkit = { group = "com.viaversion", name = "viaversion-bukkit", version.ref = "viaversion" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocollib" }
bungee = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungee" }
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
minestom = { group = "eu.darkcube", name = "minestom", version.ref = "minestom" }
minestom-extensions = { group = "dev.hollowcube", name = "minestom-ce-extensions", version.ref = "minestom-extensions" }
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jctools-core = { group = "org.jctools", name = "jctools-core", version.ref = "jctools-core" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }

cloudnet-driver = { group = "eu.cloudnetservice.cloudnet", name = "driver", version.ref = "cloudnet" }
cloudnet-bridge = { group = "eu.cloudnetservice.cloudnet", name = "bridge", version.ref = "cloudnet" }
cloudnet-node = { group = "eu.cloudnetservice.cloudnet", name = "node", version.ref = "cloudnet" }
cloudnet-wrapper = { group = "eu.cloudnetservice.cloudnet", name = "wrapper-jvm", version.ref = "cloudnet" }
cloudnet-inject-api = { group = "eu.cloudnetservice.cloudnet", name = "platform-inject-api", version.ref = "cloudnet" }
cloudnet-inject-processor = { group = "eu.cloudnetservice.cloudnet", name = "platform-inject-processor", version.ref = "cloudnet" }

[bundles]
minestom = [
    "minestom",
    "minestom-extensions"
]
adventure = [
    "adventure-api",
    "adventure-platform-bukkit",
    "adventure-text-serializer-gson",
    "adventure-text-serializer-gson-legacy-impl",
    "adventure-text-serializer-legacy",
    "adventure-text-serializer-plain"
]

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
