metadata.format.version = "1.1"

[versions]

adventure = "4.12.0"


[libraries]

adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureBukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version = "4.2.0" }
adventureTextSerializerGson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventureTextSerializerGsonLegacy = { group = "net.kyori", name = "adventure-text-serializer-gson-legacy-impl", version.ref = "adventure" }
adventureTextSerializerLegacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventureTextSerializerPlain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }

[bundles]

adventure = ["adventureApi", "adventureTextSerializerGson", "adventureTextSerializerPlain", "adventureTextSerializerGsonLegacy", "adventureTextSerializerLegacy", "adventureBukkit"]
