metadata.format.version = "1.1"

[versions]

adventure = "4.12.0"
cloudnet = "3.4.5-RELEASE"
bungee = "1.19-R0.1-SNAPSHOT"
luckperms = "5.4"
protocollib = "4.8.0"
viaversion = "4.5.1"

[libraries]

viaversion = { group = "com.viaversion", name = "viaversion-api", version.ref = "viaversion"}
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocollib" }
bungee = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungee" }
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }

cloudnetDriver = { group = "de.dytanic.cloudnet", name = "cloudnet-driver", version.ref = "cloudnet" }
cloudnetBridge = { group = "de.dytanic.cloudnet", name = "cloudnet-bridge", version.ref = "cloudnet" }
cloudnet = { group = "de.dytanic.cloudnet", name = "cloudnet", version.ref = "cloudnet" }
cloudnetWrapper = { group = "de.dytanic.cloudnet", name = "cloudnet-wrapper-jvm", version.ref = "cloudnet" }

adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureBukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version = "4.2.0" }
adventureTextSerializerGson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventureTextSerializerGsonLegacy = { group = "net.kyori", name = "adventure-text-serializer-gson-legacy-impl", version.ref = "adventure" }
adventureTextSerializerLegacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventureTextSerializerPlain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }

[bundles]

adventure = ["adventureApi", "adventureTextSerializerGson", "adventureTextSerializerPlain", "adventureTextSerializerGsonLegacy", "adventureTextSerializerLegacy", "adventureBukkit"]
