main: eu.darkcube.system.aetheria.Aetheria
name: Aetheria
author: EliteDarkness
version: 1.0
api-version: 1.13
depend: [ System ]
commands:
  gm:
    description: Wechselt den Gamemode
    permission: aetheria.gm.use
  heal:
    description: Heilt den Spieler
    permission: aetheria.heal.use
  day:
    description: Setzt Tag
    permission: aetheria.day.use
  night:
    description: Setzt Nacht
    permission: aetheria.night.use
  god:
    description: Setzt den Spieler in die Unzerstörbarkeit
    permission: aetheria.god.use
  fly:
    description: Setzt den Spieler in den Flugmodus
    permission: aetheria.fly.use
  feed:
    description: Füttert den Spieler
    permission: aetheria.feed.use
  max:
    description: Maximiert die Werte des Spielers
    permission: aetheria.max.use
  trash:
    description: Öffnet einen Mülleimer
    permission: aetheria.trash.use
  warp:
    description: Öffnet die Warp-Punkte
    permission: aetheria.warp.use
  spawn:
    description: Teleportiert den Spieler zum Spawn
    permission: aetheria.spawn.use
  getitem:
    description: Öffnet ein Inventar mit custom Items
    permission: aetheria.getitem.use
  killmobs:
    description: Tötet alle Mobs in der Welt des Spielers
    permission: aetheria.killmobs.use
  addxp:
    description: Gibt dem Spieler custom XP
    permission: aetheria.addxp.use
  mylevel:
    description: Zeigt dein aktuelles Level
    permission: aetheria.mylevel.use
  resetlevel:
    description: Setzt dein Level und XP auf 0 zurück
    permission: aetheria.resetlevel.use
  myxp:
    description: Zeigt die aktuellen benutzerdefinierten XP des Spielers an
    permission: aetheria.myxp.use
  myap:
    description: Zeigt die aktuellen AP des Spielers an
    permission: aetheria.myap.use
  attribute:
    description: Öffnet die Attribute
    aliases: [ attr ]
    permission: aetheria.attribute.use
  addhealth:
    description: Gibt dem Spieler custom Health
    permission: aetheria.addhealth.use
  myhealth:
    description: Zeigt die aktuellen benutzerdefinierten Health des Spielers an
    permission: aetheria.myhealth.use
  addregeneration:
    description: Gibt dem Spieler custom Regeneration
    permission: aetheria.addregeneration.use
  addarounddamage:
    description: Fügt AroundDamage zu einem Spieler hinzu
    permission: aetheria.addarounddamage.use
  myarounddamage:
    description: Zeigt den AroundDamage des Spielers an
    permission: aetheria.myarounddamage.use
  adddefense:
    description: Gibt dem Spieler custom Defense
    permission: aetheria.adddefense.use
  mydefense:
    description: Zeigt die aktuelle benutzerdefinierte Defense des Spielers an
    permission: aetheria.mydefense.use
  myregeneration:
    description: Zeigt den Regenerationswert des Spielers an
    permission: aetheria.myregeneration.use
  additemlevel:
    description: Erhöht das ItemLevel des Gegenstands in der Hand des Spielers
    permission: aetheria.additemlevel.use
  resetdurability:
    description: Setzt die Haltbarkeit des gehaltenen CustomSword-Items zurück
    permission: aetheria.resetdurability.use
  spawnupgrader:
    description: Spawnt einen Upgrader NPC
    permission: aetheria.spawnupgrader.use
  mycor:
    description: Zeigt die aktuellen Cor des Spielers an
    permission: aetheria.mycor.use
  addcor:
    description: Gibt dem Spieler Cor
    permission: aetheria.addcor.use
  setcor:
    description: Setzt dem Spieler Cor
    permission: aetheria.setcor.use
  adddamage:
    description: Gibt dem Spieler custom Damage
    permission: aetheria.adddamage.use
  mydamage:
    description: Zeigt den aktuellen benutzerdefinierten Damage des Spielers an
    permission: aetheria.mydamage.use
  addskillslot:
    description: Setzt die Skills auf die Skillslots
    permission: aetheria.addskillslot.use
  myskills:
    description: Zeigt die Skills auf den Skillslots
    permission: aetheria.myskills.use
  useskill:
    description: Aktiviere einen benutzerdefinierten Skill
    permission: aetheria.useskill.use
  useskillslot:
    description: Aktiviere einen Skill auf einen Skillslot
    permission: aetheria.useskillslot.use
  skills:
    description: Öffne das Skill-Inventar
    permission: aetheria.skills.use
  myitemlevel:
    description: Zeigt das Level des Items im Hauptslot des Spielers an
    permission: aetheria.myitemlevel.use
  myitemdurability:
    description: Zeigt die Durability des Items im Hauptslot des Spielers an
    permission: aetheria.myitemdurability.use

    default: op
  aetheria.heal.use:
    default: op
  aetheria.day.use:
    default: op
  aetheria.night.use:
    default: op
  aetheria.god.use:
    default: op
  aetheria.fly.use:
    default: op
  aetheria.feed.use:
    default: op
  aetheria.max.use:
    default: op
  aetheria.trash.use:
    default: not op
  aetheria.warp.use:
    default: not op
  aetheria.spawn.use:
    default: not op
  aetheria.getitem.use:
    default: op
  aetheria.killmobs.use:
    default: op
  aetheria.addxp.use:
    default: op
  aetheria.mylevel.use:
    default: not op
  aetheria.resetlevel.use:
    default: op
  aetheria.myxp.use:
    default: not op
  aetheria.myap.use:
    default: not op
  aetheria.attribute.use:
    default: not op
  aetheria.addhealth.use:
    default: op
  aetheria.myhealth.use:
    default: not op
  aetheria.addregeneration.use:
    default: op
  aetheria.addarounddamage.use:
    default: op
  aetheria.myarounddamage.use:
    default: op
  aetheria.adddefense.use:
    default: op
  aetheria.mydefense.use:
    default: op
  aetheria.myregeneration.use:
    default: op
  aetheria.additemlevel.use:
    default: op
  aetheria.itemlevel.use:
    default: op
  aetheria.resetdurability.use:
    default: op
  aetheria.spawnupgrader.use:
    default: op
  aetheria.mycor.use:
    default: not op
  aetheria.addcore.use:
    default: op
  aetheria.setcore.use:
    default: op
  aetheria.mydamage.use:
    default: not op
  aetheria.adddamage.use:
    default: op
  aetheria.addskillslot.use:
    default: not op
  aetheria.myskills.use:
    default: not op
  aetheria.useskill.use:
    default: not op
  aetheria.useskillslot.use:
    default: not op
  aetheria.skills.use:
    default: not op
  aetheria.myitemlevel.use:
    default: not op
  aetheria.myitemdurability.use:
    default: not op