main: eu.darkcube.system.aetheria.Aetheria
name: Aetheria
author: EliteDarkness
version: 1.0
api-version: 1.13
depend: [ System ]
commands:
  gm:
    description: Wechselt den Gamemode
  heal:
    description: Heilt den Spieler
  day:
    description: Setzt Tag
  night:
    description: Setzt Nacht
  god:
    description: Setzt den Spieler in die Unzerstörbarkeit
  fly:
    description: Setzt den Spieler in den Flugmodus
  feed:
    description: Füttert den Spieler
  max:
    description: Maximiert die Werte des Spielers
  trash:
    description: Öffnet einen Mülleimer
  warp:
    description: Öffnet die Warp-Punkte
  spawn:
    description: Teleportiert den Spieler zum Spawn
  getitem:
    description: Öffnet ein Inventar mit custom Items
  killmobs:
    description: Tötet alle Mobs in der Welt des Spielers
  addxp:
    description: Gibt dem Spieler custom XP
  mylevel:
    description: Zeigt dein aktuelles Level
  resetlevel:
    description: Setzt dein Level und XP auf 0 zurück
  myxp:
    description: Zeigt die aktuellen benutzerdefinierten XP des Spielers an
  myap:
    description: Zeigt die aktuellen AP des Spielers an
  attribute:
    description: Öffnet die Attribute
    aliases: [ attr ]
  addhealth:
    description: Gibt dem Spieler custom Health
  myhealth:
    description: Zeigt die aktuellen benutzerdefinierten Health des Spielers an
  addregeneration:
    description: Gibt dem Spieler custom Regeneration
  addarounddamage:
    description: Fügt AroundDamage zu einem Spieler hinzu
  myarounddamage:
    description: Zeigt den AroundDamage des Spielers an
  adddefense:
    description: Gibt dem Spieler custom Defense
  mydefense:
    description: Zeigt die aktuelle benutzerdefinierte Defense des Spielers an
  myregeneration:
    description: Zeigt den Regenerationswert des Spielers an
  additemlevel:
    description: Erhöht das ItemLevel des Gegenstands in der Hand des Spielers
  itemlevel:
    description: Zeigt das Level des Items im Hauptslot des Spielers an
  resetdurability:
    description: Setzt die Haltbarkeit des gehaltenen CustomSword-Items zurück
  spawnupgrader:
    description: Spawnt einen Upgrader NPC
  mycor:
    description: Zeigt die aktuellen Cor des Spielers an
  addcor:
    description: Gibt dem Spieler Cor
  setcor:
    description: Setzt dem Spieler Cor
  adddamage:
    description: Gibt dem Spieler custom Damage
  mydamage:
    description: Zeigt den aktuellen benutzerdefinierten Damage des Spielers an
  addskillslot:
    description: Setzt die Skills auf die Skillslots
  myskills:
    description: Zeigt die Skills auf den Skillslots
  useskill:
    description: Aktiviere einen benutzerdefinierten Skill
  useskillslot:
    description: Aktiviere einen Skill auf einen Skillslot

permissions:
  gm.use:
    default: op
  heal.use:
    default: op
  day.use:
    default: op
  night.use:
    default: op
  god.use:
    default: op
  fly.use:
    default: op
  feed.use:
    default: op
  max.use:
    default: op
  trash.use:
    default: not op
  warp.use:
    default: not op
  spawn.use:
    default: not op
  getitem.use:
    default: op
  killmobs.use:
    default: op
  addxp.use:
    default: op
  mylevel.use:
    default: not op
  resetlevel.use:
    default: op
  myxp.use:
    default: not op
  myap.use:
    default: not op
  attribute.use:
    default: not op
  addhealth.use:
    default: op
  myhealth.use:
    default: not op
  addregeneration.use:
    default: op
  addarounddamage.use:
    default: op
  myarounddamage.use:
    default: op
  adddefense.use:
    default: op
  mydefense.use:
    default: op
  myregeneration.use:
    default: op
  additemlevel.use:
    default: op
  itemlevel.use:
    default: op
  resetdurability.use:
    default: op
  spawnupgrader.use:
    default: op
  mycor.use:
    default: not op
  addcore.use:
    default: op
  setcore.use:
    default: op
  mydamage.use:
    default: not op
  adddamage.use:
    default: op
  addskillslot.use:
    default: not op
  myskills.use:
    default: not op
  useskill.use:
    default: not op
  useskillslot.use:
    default: not op
