commandprefix: '§5Wool§dBattle'
tabprefix: '&1Wool&2Battle'
name: '&5DarkCube.eu'
at_all: '@a'
at_team: '@t'
minplayercount: 2
maxblockarrowhits: 3
spawnprotectionticks: 80
spawnprotectionticksglobal: 600

scoreboard:
   displayname: '&5DarkCube.eu'
