main: eu.darkcube.system.sumo.Sumo
name: Sumo
author: EliteDarkness
version: 2.0
api-version: 1.8
depend: [System]

commands:
  mapvote:
    description: Votet für die Maps
    permission: sumo.mapvote.use
  showactivemap:
    description: Zeigt die Aktive Map an
    permission: sumo.showactivemap.use
  tpactiveworld:
    description: Teleportiert sich zur aktiven Map
    permission: sumo.tpactiveworld.use


Permissions:
  sumo.mapvote.use:
    default: op
  sumo.showactivemap.use:
    default: op
  sumo.tpactiveworld.use:
    default: op
