main: eu.darkcube.system.sumo.Sumo
name: Sumo
author: EliteDarkness
version: 2.0
api-version: 1.8
depend: [System]

commands:
  mapvote:
    description: Votet für die Maps
    permission: sumo.mapvote.use
  showactivemap:
    description: Zeigt die Aktive Map an
    permission: sumo.showactivemap.use
  tpactiveworld:
    description: Teleportiert sich zur aktiven Map
    permission: sumo.tpactiveworld.use
  showgamestate:
    description: Zeigt den Game Status
    permission: sumo.showgamestate.use
  setgamestate:
    description: Setzt den Game Status
    permission: sumo.setgamestate.use
  timer:
    description: Setzt den Timer
    permission: sumo.timer.use


Permissions:
  sumo.mapvote.use:
    default: op
  sumo.showactivemap.use:
    default: op
  sumo.tpactiveworld.use:
    default: op
  sumo.showgamestate.use:
    default: op
  sumo.setgamestate.use:
    default: op
  sumo.timer.use:
    default: op
