main: eu.darkcube.system.citybuild.listener.Citybuild
name: CityBuild
author: EliteDarkness
version: 1.0
api-version: 1.13
commands:
  gm:
    description: Wechselt den Gamemode
  heal:
    description: Heilt den Spieler
  day:
    description: Setzt Tag
  night:
    description: Setzt Nacht
  god:
    description: Setzt den Spieler in die Unzerstörbarkeit
  fly:
    description: Setzt den Spieler in den Flugmodus
  feed:
    description: Füttert den Spieler
  max:
    description: Maximiert die Werte des Spielers
  trash:
    description: Öffnet einen Mülleimer
  warp:
    description: Öffnet die Warp-Punkte
  spawn:
    description: Teleportiert den Spieler zum Spawn
  getitem:
    description: Öffnet ein Inventar mit custom Items
  killmobs:
    description: Tötet alle Mobs in der Welt des Spielers
  addxp:
    description: Gibt dem Spieler custom XP
  mylevel:
    description: Zeigt dein aktuelles Level
  resetlevel:
    description: Setzt dein Level und XP auf 0 zurück
  myxp:
    description: Zeigt die aktuellen benutzerdefinierten XP des Spielers an
  myap:
    description: Zeigt die aktuellen AP des Spielers an
  attribute:
    description: Öffnet die Attribute
    aliases: [attr]
  addhealth:
    description: Gibt dem Spieler custom Health
  myhealth:
    description: Zeigt die aktuellen benutzerdefinierten Health des Spielers an
  addregeneration:
    description: Gibt dem Spieler custom Regeneration
  addarounddamage:
    description: Fügt AroundDamage zu einem Spieler hinzu
  myarounddamage:
    description: Zeigt den AroundDamage des Spielers an
  adddefense:
    description: Gibt dem Spieler custom Defense
  mydefense:
    description: Zeigt die aktuelle benutzerdefinierte Defense des Spielers an
  myregeneration:
    description: Zeigt den Regenerationswert des Spielers an

permissions:
  gm.use:
    default: op
  heal.use:
    default: op
  day.use:
    default: op
  night.use:
    default: op
  god.use:
    default: op
  fly.use:
    default: op
  feed.use:
    default: op
  max.use:
    default: op
  trash.use:
    default: not op
  warp.use:
    default: not op
  spawn.use:
    default: not op
  getitem.use:
    default: op
  killmobs.use:
    default: op
  addxp.use:
    default: op
  mylevel.use:
    default: not op
  resetlevel.use:
    default: op
  myxp.use:
    default: not op
  myap.use:
    default: not op
  attribute.use:
    default: not op
  addhealth.use:
    default: op
  myhealth.use:
    default: not op
  addregeneration.use:
    default: op
  addarounddamage.use:
    default: op
  myarounddamage.use:
    default: op
  adddefense.use:
    default: op
  mydefense.use:
    default: op
  myregeneration.use:
    default: op
