main: eu.darkcube.system.citybuild.commands.Citybuild
name: CityBuild
author: EliteDarkness
version: 1.0
api-version: 1.13
commands:
  gm:
    description: Wechselt den Gamemode
  heal:
    description: Heilt den Spieler
  day:
    description: Setzt Tag
  night:
    description: Setzt Nacht
  god:
    description: Setzt den Spieler in die Unzerstörbarkeit
  fly:
    description: Setzt den Spieler in den Flugmodus
  feed:
    description: Füttert den Spieler
  max:
    description: Maximiert die Werte des Spielers
  trash:
    description: Öffnet einen Mülleimer
  warp:
    description: Öffnet die Warp-Punkte
  spawn:
    description: Teleportiert den Spieler zum Spawn
  getitem:
    description: Öffnet ein Inventar mit custom Items
  killmobs:
    description: Tötet alle Mobs in der Welt des Spielers

permissions:
  gm.use:
    default: op
  heal.use:
    default: op
  day.use:
    default: op
  night.use:
    default: op
  god.use:
    default: op
  fly.use:
    default: op
  feed.use:
    default: op
  max.use:
    default: op
  trash.use:
    default: not op
  warp.use:
    default: not op
  spawn.use:
    default: not op
  getitem.use:
    default: op
  killmobs.use:
    default: op
