package building.oneblock.util;

import org.bukkit.Material;
import java.util.List;
import java.util.Map;

public class StageBlocks {

    public static Map<Integer, List<Material>> createStageBlocksMap() {
        return Map.of(
                1, List.of(
                        Material.GRASS_BLOCK,
                        Material.DIRT,
                        Material.STONE,
                        Material.OAK_LOG,
                        Material.OAK_LEAVES,
                        Material.SPRUCE_LOG,
                        Material.BIRCH_LOG,
                        Material.COBBLESTONE,
                        Material.SAND,
                        Material.GRAVEL),
                2, List.of(
                        Material.GRASS_BLOCK,
                        Material.DIRT,
                        Material.STONE,
                        Material.OAK_LOG,
                        Material.OAK_LEAVES,
                        Material.SPRUCE_LOG,
                        Material.BIRCH_LOG,
                        Material.COBBLESTONE,
                        Material.SAND,
                        Material.GRAVEL,
                        Material.DARK_OAK_LOG,
                        Material.ACACIA_LOG,
                        Material.JUNGLE_LOG,
                        Material.COAL_ORE,
                        Material.IRON_ORE,
                        Material.CLAY,
                        Material.TERRACOTTA,
                        Material.PACKED_ICE,
                        Material.MAGMA_BLOCK),
                3, List.of(
                        Material.DARK_OAK_LOG,
                        Material.ACACIA_LOG,
                        Material.JUNGLE_LOG,
                        Material.COAL_ORE,
                        Material.IRON_ORE,
                        Material.CLAY,
                        Material.TERRACOTTA,
                        Material.PACKED_ICE,
                        Material.MAGMA_BLOCK,
                        Material.WHEAT,
                        Material.POTATO,
                        Material.CARROT,
                        Material.BEETROOT_SEEDS,
                        Material.PUMPKIN_SEEDS,
                        Material.MELON_SEEDS,
                        Material.SUGAR_CANE,
                        Material.CACTUS),
                4, List.of(
                        Material.WHEAT,
                        Material.POTATO,
                        Material.CARROT,
                        Material.BEETROOT_SEEDS,
                        Material.PUMPKIN_SEEDS,
                        Material.MELON_SEEDS,
                        Material.SUGAR_CANE,
                        Material.CACTUS,
                        Material.BRICKS,
                        Material.STONE_BRICKS,
                        Material.MOSSY_COBBLESTONE,
                        Material.OBSIDIAN,
                        Material.NETHERRACK,
                        Material.SOUL_SAND,
                        Material.GLOWSTONE),
                5, List.of(
                        Material.BRICKS,
                        Material.STONE_BRICKS,
                        Material.MOSSY_COBBLESTONE,
                        Material.OBSIDIAN,
                        Material.NETHERRACK,
                        Material.SOUL_SAND,
                        Material.GLOWSTONE,
                        Material.DIAMOND_ORE,
                        Material.LAPIS_ORE,
                        Material.REDSTONE_ORE,
                        Material.EMERALD_ORE,
                        Material.NETHER_QUARTZ_ORE,
                        Material.GOLD_ORE,
                        Material.NETHER_GOLD_ORE),
                6, List.of(
                        Material.DIAMOND_ORE,
                        Material.LAPIS_ORE,
                        Material.REDSTONE_ORE,
                        Material.EMERALD_ORE,
                        Material.NETHER_QUARTZ_ORE,
                        Material.GOLD_ORE,
                        Material.NETHER_GOLD_ORE,
                        Material.END_STONE,
                        Material.SHULKER_BOX,
                        Material.WITHER_SKELETON_SKULL),
                7, List.of(
                        Material.NETHER_GOLD_ORE,
                        Material.END_STONE,
                        Material.SHULKER_BOX,
                        Material.WITHER_SKELETON_SKULL,
                        Material.SEA_LANTERN,
                        Material.PRISMARINE,
                        Material.DARK_PRISMARINE,
                        Material.SLIME_BLOCK,
                        Material.HONEY_BLOCK,
                        Material.AMETHYST_BLOCK,
                        Material.COPPER_BLOCK)
        );
    }

}
