main: eu.darkcube.system.woolbattleteamfight.Main
name: WoolBattleTeamfight
author: EliteDarkness
version: 1.0
api-version: 1.8
depend: [System]

commands:
  timer:
    description: Setzt den Lobby Timer
    permission: woolbattleteamfight.timer.use
  start:
    description: Starte das Spiel
    permission: woolbattleteamfight.start.use

  woolbattleteamfight.timer.use:
    default: op
  woolbattleteamfight.start.use:
    default: op