package eu.darkcube.system.lobbysystem.inventory.abstraction;

public enum InventoryType {

	LOADING,
	PLAYER,
	COMPASS,
	LOBBY_SWITCHER,
	GADGET,
	SETTINGS,
	WOOLBATTLE,
	DAILY_REWARD,
	PSERVER,
	PSERVER_OWN,
	PSERVER_SLOT,
	GAMESERVER_SELECTION_WOOLBATTLE,
	GAMESERVER_SELECTION,
	PSERVER_CONFIGURATION,
	CONFIRM,

}
