commandprefix: '§5Wool§dBattle'
tabprefix: '&1Wool&2Battle'
name: '&5DarkCube.eu'
at_all: '@a'
at_team: '@t'
minplayercount: 2
maxblockarrowhits: 3
spawnprotectionticks: 80
spawnprotectionticksglobal: 600
tab:
   header: '\n%name%\n%prefix%\n'
   footer: '\n&7Server: &6%server%\n&7Map: &6%map%\n'
   
scoreboard:
   displayname: '&5DarkCube.eu'